### PR TITLE
Adds new function BE_PBKDF2_HMAC.

### PR DESCRIPTION
**Pull request by harawata**
Hi,

This PR adds a new function that generates a derived key from a password along with a salt using [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2).
Attached a brief documentation at the bottom.
I am not sure if you guys accept contributions like this, so feel free to close this if you don't.

As I don't have Windows build environment, it's tested only on macOS 10.12.3 with FMPA 14.0.6.
This fmp12 file contains test records for the function : [Tests_BE_PBKDF2_HMAC.fmp12.zip](https://github.com/GoyaPtyLtd/BaseElements-Plugin/files/785054/Tests_BE_PBKDF2_HMAC.fmp12.zip)
Let me know if there is anything I should change.

Regards,
Iwao

---

#### BE\_PBKDF2\_HMAC ( password ; salt ; iterations {; hashLength ; algorithm ; outputEncoding ; inputEncoding } )

Derives a key from a password with a specified salt and iteration count using PBKDF2.

Version : 

__Parameters__ :

password : The password used in the key derivation.
salt : The salt used in the key derivation.
iterations : The iteration count.  Possible value is greater than or equal to 1. The default value is 1000.
hashLength ( optional ) : The desired length of the derived key in bytes. The default value is 20.
algorithm ( optional ) : Possible values are any of the _BE\_MessageDigestAlgorithm_ options, with a default of _BE\_MessageDigestAlgorithm\_SHA1_. 
outputEncoding ( optional ) : Possible values are _BE\_Encoding\_Hex_ or _BE\_Encoding\_Base64_ with hex being the default.
inputEncoding ( optional ) : Possible values are _BE\_Encoding\_Hex_ or _BE\_Encoding\_Base64_. Treated as UTF-8 string if not specified.

__Result__ : The derived key.

__Notes__ : the "input" encoding applies to both the password and the salt.  So in some situations, such as AWS, you get a value in Hex encoding, and then need to re-apply that with a value in Base64.  You can't mix and match encodings in this function, so one needs to be changed.  You can use custom functions within FileMaker to convert encoding formats.  Custom Functions such as DecToHex or StringToHex are fairly easily found on the web.

### CODE REVIEW

**Comment by nickorr** [comment]
Iwao,

This is fantastic.  Yes, we do certainly accept patches like this.  We'll have a look over it to see if there's any issues integrating it with the rest, and if not, bring it into the v4 so we can test on Mac and Win.

I'll also send you a link to the sponsors dropbox share in return for your hard work.

Cheers,
Nick

**Comment by harawata** [comment]
Awesome! Thank you for your time!

**Comment by nickorr** [comment]
Iwao,

Send me your preferred email address to nick@goya.com.au

Cheers,
Nick

**Comment by harawata** [comment]
Sent an email with subject 'Regarding pull request #129'.

**Comment by nickorr** [comment]
Iwao,

I'm guessing now that this request is no longer required, because of the changes in v16 with the native functions?  Or is this not the case, and you'd still like to see this added in.

Cheers,
Nick

**Comment by harawata** [comment]
Hi @nickorr ,
I think there still is no native function with the same functionality, but let's close this for now.
I may be able to work on this again if someone is interested in this in future.

**Comment by nickorr** [comment]
No worries.  I'm happy to have it put back in if you need it, or if there's nothing equivalent.  I don't understand enough about all this to know where it fits in.

I had a look back over my notes too, and there were some differences in how it was done at the time such that it seemed like it would have been easier to make these changes manually ( because of other changes to the code base around the same time. )

So if you're still keen to see this in the plugin, I'd love for you to submit a new request for it against the current code base.

( And sorry this took so long to get to. )

Cheers,
Nick

**Comment by harawata** [comment]
Cool!
It seems that PBKDF2 still is a viable option when calculating password hash, so I'll find some time and rewrite it.

And please do not worry about the delay.
I just wanted to contribute something in appreciation of your work. :)

**Pull request closed without merging**
